In [2]:
import pandas as pd
from matplotlib import pyplot as plt
from pathlib import Path
# import ipywidgets as widgets

In [4]:
# csv_folder = Path('../csv').resolve()
# assert csv_folder.exists(), f'csv folder does not exist: {csv_folder}'
# csv_files = csv_folder.glob('**/emg_*.csv')
# csv_files = list(csv_files)
# csv_files

# Path('/home/user1/Downloads/wandb_export_nonoise_cifar10_sgd_dp.csv'),
#  Path('/home/user1/Downloads/eps8_epoch15_sgd_dp.csv'),
# csv_files = [ Path('/home/user1/Downloads/wandb_export_gep_eps8_epochs15.csv')]
csv_files = [ Path('/home/user1/Downloads/eps8_epoch30_gep_public.csv')]
csv_files, [f.exists() for f in csv_files]

([PosixPath('/home/user1/Downloads/eps8_epoch30_gep_public.csv')], [True])

In [5]:
df_list = [pd.read_csv(f.as_posix()) for f in csv_files]

df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)
df

,Name,basis_size,clip,eps,global_lr,gradients_history_size,lr,lr_dec_rate,n_epochs,seed,wd,val_avg_acc,test_acc
0,basis_size_50_clip_0.3890158079244423_eps_8_gl...,50,0.389016,8,0.403185,500,0.001964,1,30,42,0.001,0.106401,0.268885
1,basis_size_50_clip_0.409888492246116_eps_8_glo...,50,0.409888,8,0.326381,500,0.009962,1,30,43,0.001,0.185271,0.266295
2,basis_size_50_clip_0.554178735757221_eps_8_glo...,50,0.554179,8,0.291904,500,0.029277,1,30,43,0.001,0.170375,0.230508
3,basis_size_50_clip_0.4474676548106513_eps_8_gl...,50,0.447468,8,0.206138,500,0.030023,1,30,43,0.001,0.141977,0.251191
4,basis_size_50_clip_0.9406979076332976_eps_8_gl...,50,0.940698,8,0.402414,500,0.001384,1,30,42,0.001,0.192686,0.279656
5,basis_size_50_clip_0.5638321329583802_eps_8_gl...,50,0.563832,8,0.286956,500,0.026777,1,30,43,0.001,0.184151,0.250238
6,basis_size_50_clip_0.7126537559642396_eps_8_gl...,50,0.712654,8,0.347164,500,0.019686,1,30,43,0.001,0.192734,0.252824
7,basis_size_50_clip_0.8842680569276542_eps_8_gl...,50,0.884268,8,0.245615,500,0.003771,1,30,44,0.001,0.144949,0.243458
8,basis_size_50_clip_0.8621330566881338_eps_8_gl...,50,0.862133,8,0.255830,500,0.012944,1,30,44,0.001,0.189954,0.220441
9,basis_size_50_clip_0.9414628906219082_eps_8_gl...,50,0.941463,8,0.307040,500,0.042107,1,30,43,0.001,0.101483,0.255001
10,basis_size_50_clip_0.7185812892853807_eps_8_gl...,50,0.718581,8,0.336688,500,0.024401,1,30,44,0.001,0.099410,0.185094
11,basis_size_50_clip_0.9492697505992282_eps_8_gl...,50,0.949270,8,0.240746,500,0.092160,1,30,44,0.001,0.101330,0.177011

In [7]:
df[df['test_acc'] > 0.21]

,Name,basis_size,clip,eps,global_lr,gradients_history_size,lr,lr_dec_rate,n_epochs,seed,wd,val_avg_acc,test_acc
0,basis_size_50_clip_0.3890158079244423_eps_8_gl...,50,0.389016,8,0.403185,500,0.001964,1,30,42,0.001,0.106401,0.268885
1,basis_size_50_clip_0.409888492246116_eps_8_glo...,50,0.409888,8,0.326381,500,0.009962,1,30,43,0.001,0.185271,0.266295
2,basis_size_50_clip_0.554178735757221_eps_8_glo...,50,0.554179,8,0.291904,500,0.029277,1,30,43,0.001,0.170375,0.230508
3,basis_size_50_clip_0.4474676548106513_eps_8_gl...,50,0.447468,8,0.206138,500,0.030023,1,30,43,0.001,0.141977,0.251191
4,basis_size_50_clip_0.9406979076332976_eps_8_gl...,50,0.940698,8,0.402414,500,0.001384,1,30,42,0.001,0.192686,0.279656
5,basis_size_50_clip_0.5638321329583802_eps_8_gl...,50,0.563832,8,0.286956,500,0.026777,1,30,43,0.001,0.184151,0.250238
6,basis_size_50_clip_0.7126537559642396_eps_8_gl...,50,0.712654,8,0.347164,500,0.019686,1,30,43,0.001,0.192734,0.252824
7,basis_size_50_clip_0.8842680569276542_eps_8_gl...,50,0.884268,8,0.245615,500,0.003771,1,30,44,0.001,0.144949,0.243458
8,basis_size_50_clip_0.8621330566881338_eps_8_gl...,50,0.862133,8,0.255830,500,0.012944,1,30,44,0.001,0.189954,0.220441
9,basis_size_50_clip_0.9414628906219082_eps_8_gl...,50,0.941463,8,0.307040,500,0.042107,1,30,43,0.001,0.101483,0.255001

In [9]:
best = df.groupby(['seed'])['test_acc'].max()
best.mean(), best.std()

(0.26313637893229974, 0.018304704558408425)

In [4]:
csv_files = [ Path('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed42.csv'), Path('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed43.csv'), Path('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed44.csv')]
csv_files, [f.exists() for f in csv_files]

([PosixPath('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed42.csv'),
  PosixPath('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed43.csv'),
  PosixPath('/home/user1/Downloads/eps8_epoch30_sgd_dp_seed44.csv')],
 [True, True, True])

In [5]:
df_list = [pd.read_csv(f.as_posix()) for f in csv_files]

df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)
df

,Name,clip,eps,global_lr,lr,lr_dec_rate,n_epochs,seed,wd,val_avg_acc,test_acc
0,clip_0.04349425299412385_eps_8_global_lr_0.829...,0.043494,8,0.829737,0.019508,0.95,30,42,0.001,0.209748,NaN
1,clip_0.03163805361543916_eps_8_global_lr_0.919...,0.031638,8,0.919386,0.020865,1.00,30,42,0.001,0.135482,NaN
2,clip_0.03338654397101316_eps_8_global_lr_0.939...,0.033387,8,0.939599,0.021542,0.95,30,42,0.001,0.220824,0.239978
3,clip_0.03664337611720077_eps_8_global_lr_0.838...,0.036643,8,0.838273,0.022658,0.95,30,43,0.001,0.130639,NaN
4,clip_0.04322268382551331_eps_8_global_lr_0.880...,0.043223,8,0.880021,0.020846,0.95,30,42,0.001,0.195193,NaN
...,...,...,...,...,...,...,...,...,...,...,...
335,clip_0.040420130367399776_eps_8_global_lr_0.84...,0.040420,8,0.841157,0.022357,1.00,30,44,0.001,0.152627,NaN
336,clip_0.02474292649248592_eps_8_global_lr_0.928...,0.024743,8,0.928013,0.020976,0.95,30,44,0.001,0.209745,0.217016
337,clip_0.03565942566228007_eps_8_global_lr_0.815...,0.035659,8,0.815341,0.023590,0.95,30,44,0.001,0.196398,NaN
338,clip_0.02086966021320415_eps_8_global_lr_0.940...,0.020870,8,0.940010,0.020415,0.95,30,44,0.001,0.127306,NaN
339,clip_0.022693295767807337_eps_8_global_lr_0.90...,0.022693,8,0.903247,0.021748,1.00,30,44,0.001,0.205905,0.210166

In [7]:
df[df['test_acc'] > 0.19]

,Name,clip,eps,global_lr,lr,lr_dec_rate,n_epochs,seed,wd,val_avg_acc,test_acc
2,clip_0.03338654397101316_eps_8_global_lr_0.939...,0.033387,8,0.939599,0.021542,0.95,30,42,0.001,0.220824,0.239978
9,clip_0.03832166149251896_eps_8_global_lr_0.898...,0.038322,8,0.898277,0.019633,1.00,30,42,0.001,0.222359,0.241069
20,clip_0.041760252295482456_eps_8_global_lr_0.87...,0.041760,8,0.878428,0.018431,1.00,30,42,0.001,0.219275,0.219662
56,clip_0.03320806678603736_eps_8_global_lr_0.909...,0.033208,8,0.909063,0.019542,0.95,30,42,0.001,0.220217,0.226343
80,clip_0.03184441948154111_eps_8_global_lr_0.926...,0.031844,8,0.926814,0.022901,0.95,30,42,0.001,0.224456,0.243796
81,clip_0.03507288204546061_eps_8_global_lr_0.904...,0.035073,8,0.904693,0.023202,0.95,30,42,0.001,0.220384,0.238615
97,clip_0.04296694739521194_eps_8_global_lr_0.810...,0.042967,8,0.810869,0.023362,0.95,30,42,0.001,0.213319,0.224843
138,clip_0.024767484779219424_eps_8_global_lr_0.82...,0.024767,8,0.824210,0.019887,0.95,30,42,0.001,0.236124,0.257431
145,clip_0.033354189944368735_eps_8_global_lr_0.81...,0.033354,8,0.819884,0.020740,0.95,30,43,0.001,0.205692,0.237039
182,clip_0.042456214344730736_eps_8_global_lr_0.91...,0.042456,8,0.916502,0.019613,1.00,30,43,0.001,0.202573,0.231188
232,clip_0.029014116587800017_eps_8_global_lr_0.80...,0.029014,8,0.809991,0.018178,1.00,30,43,0.001,0.202392,0.238944
241,clip_0.03263998498335568_eps_8_global_lr_0.862...,0.032640,8,0.862741,0.019678,0.95,30,43,0.001,0.203603,0.237311
249,clip_0.026940278907129876_eps_8_global_lr_0.94...,0.026940,8,0.943423,0.018702,1.00,30,43,0.001,0.203224,0.236903
250,clip_0.036243346504069594_eps_8_global_lr_0.81...,0.036243,8,0.812377,0.022441,1.00,30,43,0.001,0.200575,0.232549
272,clip_0.0453242891751974_eps_8_global_lr_0.9087...,0.045324,8,0.908758,0.020142,1.00,30,44,0.001,0.195317,0.207563
336,clip_0.02474292649248592_eps_8_global_lr_0.928...,0.024743,8,0.928013,0.020976,0.95,30,44,0.001,0.209745,0.217016
339,clip_0.022693295767807337_eps_8_global_lr_0.90...,0.022693,8,0.903247,0.021748,1.00,30,44,0.001,0.205905,0.210166

In [10]:
best = df.groupby(['seed'])['test_acc'].max()
# best
best.mean(), best.std()

(0.23779708208005648, 0.02023195574338004)

In [6]:
csv_files = [ Path('/home/user1/Downloads/eps1_epoch15_sgd_dp_seed42.csv'), Path('/home/user1/Downloads/eps1_epoch15_gep_seed42.csv')]
csv_files, [f.exists() for f in csv_files] 
df_list = [pd.read_csv(f.as_posix()) for f in csv_files]

# df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)
# df
for df in df_list:
    best = df.groupby(['seed'])['val_avg_acc'].max()
    print(best)
    # print(best.mean(), best.std())

seed
42    0.114697
Name: val_avg_acc, dtype: float64
seed
42    0.141210
43    0.246276
44    0.206987
Name: val_avg_acc, dtype: float64

In [87]:
res = widgets.RadioButtons(
    options=['SGD_DP', 'GEP_PUBLIC', 'GEP_PRIVATE'],
    description='DP method:',
    disabled=False
)


# Display the radio button widget
display(res)

RadioButtons(description='DP method:', options=('SGD_DP', 'GEP_PUBLIC', 'GEP_PRIVATE'), value='SGD_DP')

In [98]:
good_acc = df[(df['dp_method'] == res.value)]
# good_acc = df[(df['dp_method'] == res.value) & (df['test_avg_acc'] > 0.1)]
good_acc.groupby(['noise-multiplier'])['test_avg_acc'].max()

noise-multiplier
0.000     0.607075
2.016     0.607075
4.720     0.607075
12.790    0.607075
25.000    0.615040
Name: test_avg_acc, dtype: float64

In [99]:
good_acc

,data_name,num-steps,optimizer,lr,num-client-agg,clip,noise-multiplier,seed,history_size,dp_method,epoch_of_best_val,best_val_acc,test_avg_acc
0,putEMG,264,adam,0.010,5,1.00,0.0,42,50,GEP_PUBLIC,34,0.609512,0.607075
1,putEMG,264,adam,0.010,5,0.10,0.0,42,50,GEP_PUBLIC,34,0.609512,0.607075
2,putEMG,264,adam,0.010,5,0.01,0.0,42,50,GEP_PUBLIC,29,0.609512,0.607075
3,putEMG,264,adam,0.001,5,1.00,0.0,42,50,GEP_PUBLIC,29,0.609512,0.607075
4,putEMG,264,adam,0.001,5,0.10,0.0,42,50,GEP_PUBLIC,29,0.609512,0.607075
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,putEMG,264,adam,0.010,5,0.10,25.0,41,100,GEP_PUBLIC,34,0.609512,0.607075
58,putEMG,264,adam,0.010,5,0.10,25.0,42,100,GEP_PUBLIC,29,0.609512,0.607075
59,putEMG,264,adam,0.001,5,0.10,25.0,40,100,GEP_PUBLIC,29,0.609512,0.607075
60,putEMG,264,adam,0.001,5,0.10,25.0,41,100,GEP_PUBLIC,29,0.609512,0.607075
61,putEMG,264,adam,0.001,5,0.10,25.0,42,100,GEP_PUBLIC,159,0.617684,0.615040

In [95]:
good_acc.groupby(['seed'])['test_avg_acc'].std()

seed
40    0.002938
41    0.129961
42    0.249766
Name: test_avg_acc, dtype: float64